[package]
name = "telegram_types"
version = "0.1.0"
authors = ["Quan Brew <t@ioover.net>"]
repository = "https://github.com/quanbrew/telegram-types"
categories = ["api-bindings"]
license = "MIT"
description = "Types in the Telegram Bot API and their deserializers"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
